version: "3"

services:
  generator:
    build: .
    command: ["python", "-u", "generator.py"]  # "-u" runs python in unbuffered mode means logs appears instantlt without delay
    volumes:
      - shared-logs:/logs


  analyzer:
    build: .
    command: ["python", "-u", "analyzer.py"]
    depends_on:
      - generator
    volumes:
      - shared-logs:/logs

volumes:
  shared-logs:
